version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm build
      - echo Running tests...
      - npm test
      - echo Starting deployment via CDK...
      - npm run
      - echo CDK deployment completed
  post_build:
    commands:
      - echo Build completed on `date`

# Include only the files required for your application to run.
artifacts:
  files:
    - app.js
    - index.html
    - src/*
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*